services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: smart_parking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d smart_parking_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  spot-service:
    build:
      context: .
      dockerfile: services/spot/Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/smart_parking_db?sslmode=disable
      PORT: "8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy